server:
  port: 7002

eureka:
  instance:
    # hostname: localhost  #eureka服务端的实例名称
    hostname: eureka7002.com  #eureka服务端的实例名称
  client:
    #false 表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#     defaultZone: http://eureka7001.com:7001/eureka/