server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
       discovery:
         locator:
           enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
       routes:
        - id: payment-routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
           - Path=/payment/getPaymentById/**  #断言，路径相匹配的进行路由
        - id: payment-routh2 #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言，路径相匹配的进行路由
            - After=2022-11-28T16:19:35.191+08:00[Asia/Shanghai]  #当前时间以后开始有效
          filters:
            - AddRequestParameter=X-Request-Id,1024  #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: false
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
